
export const shortNames: Record<string, string> = {
    "lab": "cc.Label",
    "btn": "cc.Button",
    "spr": "cc.Sprite",
    "scr": "cc.ScrollView",
    "lay": "cc.Layout",
    "tog": "cc.Toggle",
    "tgc": "cc.ToggleContainer",
    "edt": "cc.EditBox",
    "rtx": "cc.RichText",
    "pgv": "cc.PageView",
    "prg": "cc.ProgressBar",
    "sld": "cc.Slider",
    "msk": "cc.Mask",
    "wgt": "cc.Widget",
    "uit": "cc.UITransform",
    "ani": "cc.Animation",
    "aud": "cc.AudioSource",
    "vid": "cc.VideoPlayer",
    "wbv": "cc.WebView",
    "cam": "cc.Camera",
    "gfx": "cc.Graphics",
    "pts": "cc.ParticleSystem",
    "lit": "cc.LightComponent",
    "mdl": "cc.ModelComponent",
    "skl": "cc.Skeleton",
    "ast": "cc.AnimationState",
    "acl": "cc.AnimationClip",
    "anc": "cc.AnimationController",
    "cvs": "cc.Canvas",
    "sfa": "cc.SafeArea",
    "bie": "cc.BlockInputEvents",
    "nod": "cc.Node",
};
